<div class="container">
<div class="col-md-12"><h1>Album Listings</h1></div>


<div class="col-md-12">
<!--  notice start of table and header are BEFORE the loop -->
<table class="table table-striped">
<tr>
	<th>Id</th>
	<th>Artist</th>
	<th>Album</th>
</tr>
<?php foreach($this->collectionOfAlbums as $record) : ?>

<tr>
<tr>
<!-- 
    By default, the escape() method uses the PHP htmlspecialchars() function for escaping. 
    However, depending on your environment, you may wish for escaping to occur in a different way.
    Use the setEscape() method at the controller level to tell Zend_View what escaping callback to use. 
-->


	<td><?php echo $this->escape($record['id'])?></td>
	<td><?php echo $this->escape($record['artist']);?></td>
	<td><?php echo $this->escape($record['title']);?></td>
</tr>
</tr>


<?php endforeach; ?>
</table><!-- /notice end tag is OUTSIDE the loop -->

</div><!--  /end col-md-9 -->

</div><!--  / end container -->