  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
         
          <a class="navbar-brand" href="#"><?php echo $this->projectSettings['name']?></a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/index">Home</a></li>
            <li><a href="/artists/index">Artists</a></li>
            <li><a href="/tunes/index">Tunes</a></li>
            <li><a href="/movies/index">Movies</a></li>
            <li><a href="/tour/index">Tours</a></li>
            
              <?php  $auth = Zend_Auth::getInstance(); ?>
            <?php if ($auth->hasIdentity()) : ?>
             <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Tasks <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/admin">Main Tasks</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            <?php endif; ?>
            
          </ul>
            <?php  $auth = Zend_Auth::getInstance(); ?>
            <?php if (!$auth->hasIdentity()) : ?>

          <form class="navbar-form navbar-right" action="/auth" method="post">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control" name="username" id="username" />
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control" class="password" id="password" name="password"/>
            </div>
            <button type="submit" class="btn btn-success">Admin Login</button>
          </form>
            
            <?php else: ?>
           <form class="navbar-form navbar-right" action="/auth/logout" method="post">
            <button type="submit" class="btn btn-success">Logout</button>
           </form>
            
            <?php endif; ?>
            
        </div><!--/.navbar-collapse -->
      </div>
    </div>