<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<form action="/clo/master/public/tour/booking/" method="post">

    
    
    
	<input type="hidden" name="active_tour_id"  value="<?php echo $this->active_tour_id ?>"  />
       
        
        <p>First Name:</p> <input type="text" name="name_f" id="name_f">
        
	<input type="submit" value="Booking" />
        
    
    
</form>
