
 <div class="container">

	<div class="col-md-12">
	<h1>Update Album</h1>
    </div>
   <div class="row">
	<div class="col-md-3">
	<?php echo $this->partial('admin/partials/admin_nav.phtml')?>
	
	
	</div>
	<div class="col-md-9" style='margin-top: 25px;'>
        <?php echo $this->partial('admin/partials/form_album.phtml',array('form'=>$this->form))?>
        
	</div>
</div>
	
	
</div>